"""add_post_score

Revision ID: 13d42a02406
Revises: 2356a38169ea
Create Date: 2016-01-13 15:16:59.611945

"""

# revision identifiers, used by Alembic.
revision = '13d42a02406'
down_revision = '2356a38169ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('score', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'score')
    ### end Alembic commands ###
