"""article_column

Revision ID: 171e70161dd
Revises: 2223792e165
Create Date: 2016-03-19 22:14:31.600633

"""

# revision identifiers, used by Alembic.
revision = '171e70161dd'
down_revision = '2223792e165'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_column',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('article', sa.Column('index', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'index')
    op.drop_table('article_column')
    ### end Alembic commands ###
