"""add article.body_html

Revision ID: 42eb711b50a
Revises: 49f02f2c2ea
Create Date: 2016-06-05 16:52:48.267422

"""

# revision identifiers, used by Alembic.
revision = '42eb711b50a'
down_revision = '49f02f2c2ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'body_html')
    ### end Alembic commands ###
