"""modi theme

Revision ID: ca3cb361d4
Revises: 42eb711b50a
Create Date: 2016-06-11 15:33:17.849718

"""

# revision identifiers, used by Alembic.
revision = 'ca3cb361d4'
down_revision = '42eb711b50a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('themes', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('themes', sa.Column('release_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('themes', 'release_date')
    op.drop_column('themes', 'deadline')
    ### end Alembic commands ###
